---
- hosts: all
  become: yes
  tasks:
  - name: install zabbix-agent
    apt:
        name=zabbix-agent
        state=latest
    when:
         ansible_os_family == "Debian"
    notify:
         zabbix-agent systemd
  - name: replace server
    replace:
      path: /etc/zabbix/zabbix_agentd.conf
      regexp: '^Server=(.)*'
      replace: 'Server=10.128.0.17'
  - name: replace serverActive
    replace:
      path: /etc/zabbix/zabbix_agentd.conf
      regexp: '^ServerActive=(.)*'
      replace: 'ServerActive=10.128.0.17'
  - name: replace Hostname
    replace:
      path: /etc/zabbix/zabbix_agentd.conf
      regexp: '^Hostname=(.)*'
      replace: 'Hostname={{ ansible_hostname }}'
  handlers:
  - name: zabbix-agent systemd
    systemd:
     name: zabbix-agent.service
     enabled: yes
     state: started



